module lowlevel
{
  struct MotorCmd
  {
    uint8 mode;
    float q;
    float dq;
    float tau;
    float kp;
    float kd;
    unsigned long reserve;
  };

  struct Cmd
  {
    uint8 mode_pr;
    uint8 mode_machine;
    MotorCmd motor_cmd[35];
    unsigned long reserve[4];
    unsigned long crc;
  };
};
