# sdf_path := "../gz_gepetto_humanoids_models/empty_h1_2.sdf"
sdf_path := "../gz_gepetto_humanoids_models/h1_2/h1_2_with_ground.sdf"

install:
    #!/usr/bin/env bash
    cd build
    cmake ..
    make && sudo cp libgz-unitree.so /usr/local/lib/gz-unitree/

sim logfile="with_imu_on_model.log":
    echo Dont forget to add plugin filename="gz-unitree" name="gz::unitree::UnitreePlugin" to your SDF file, in the model tag
    just multicast lo
    just install && GZ_SIM_SYSTEM_PLUGIN_PATH=/usr/local/lib/gz-unitree/ gz sim {{sdf_path}} -v 4 | rg --fixed-strings 'Remotery'
    # just install && GZ_SIM_SYSTEM_PLUGIN_PATH=/usr/local/lib/gz-unitree/ gz sim {{sdf_path}} -v 4 >{{logfile}} 2>&1
    # uvx --with strip-ansi python -c "from pathlib import Path; from strip_ansi import strip_ansi; Path('{{logfile}}').write_text(strip_ansi(Path('{{logfile}}').read_text()))"
    # diff -y --width 250 without_imu.log {{logfile}} | code --no-sandbox -

mujoco:
    #!/usr/bin/env bash
    cd ../unitree_mujoco/simulate/build
    cmake .. && make && ./unitree_mujoco

testmuj:
    just test "h1_low_level_example"

test:
    #!/usr/bin/env bash
    just multicast lo
    cd ../h1v2-Isaac
    uv run --active deploy/sim2real.py

testdemo example="h1_27dof_example":
    #!/usr/bin/env bash
    just multicast lo
    cd ../unitree_sdk2
    mkdir -p build
    cd build
    cmake ..
    make {{example}} || { echo "Build failed"; exit 1; }
    echo Starting {{example}}...
    sudo bin/{{example}} lo
    echo Done

multicast iface="lo":
    sudo route add -net 224.0.0.0 netmask 240.0.0.0 dev {{iface}} || echo "Multicast route already exists"
    sudo ifconfig {{iface}} multicast
